ublue-os-akmods-key.spec
I thought I fixed this already. oops.
=> chore: correct changelog in akmods specfile

Containerfile, build-kmod-wl.sh
=> feat: add broadcom legacy wl driver

README.md
=> docs: add broadcom-wl to list

Containerfile, README.md, build-kmod-gcadapter_oc.sh, build-kmod-steamdeck.sh
Adds kmod packages for Valve's Steam Deck platform driver, and for overclocking Nintendo's USB gamecube controller adapter.
=> Additional gaming-oriented kmods

Containerfile, README.md, build-kmod-gcadapter_oc.sh, build-kmod-steamdeck.sh, build-kmod-xone.sh, build-kmod-xpadneo.sh, ublue-os-akmods-addons.spec
Adds an additional repo file to ublue-os-akmods-addons and modifies previous work to exclusively use it.
=> Add new ublue-os/akmods copr repo, restore steamdeck and gcadapter_oc kmods

Containerfile.common, README.md, build-kmod-nct6687d.sh
=> feat: Add nct6687 kernel module for certain B550 chipset motherboards

Containerfile.common
Conflicts with ASUS kernel patches
=> fix(asus): Exclude evdi kmod

.github/workflows/build.yml
Official images aren't ready yet
=> fix: Target Fedora 40 for official images, use ci-test for 39

Containerfile.common, build-kmod-VirtualBox.sh
Adds the kernel module needed for VirtualBox
Resolves: https://github.com/ublue-os/akmods/issues/105
=> feat: Add VirtualBox kmod

Containerfile.common, README.md, build-kmod-rtl8814au.sh
=> feat: Add Realtek RTL8814AU driver

Containerfile.common, README.md, build-kmod-rtl88xxau.sh
=> feat: Add support for Realtek RTL8812AU/21AU and RTL8814AU

.github/pull_request_template.md
=> chore: add a pull_request_template.md

.github/workflows/build.yml
These steps are known to potentially fail due to
environmental/infrastructure reasons.
Retries helps builds succeed despite that.
=> chore(ci): retry occasionally spurious steps

.github/workflows/reusable-build.yml
bring main into alignment with hwe and bluefin with concurrency group cancels, etc.
=> chore(ci): add concurrency group

.github/workflows/reusable-build.yml, Containerfile.nvidia, build-kmod-nvidia.sh, build-ublue-os-nvidia-addons.sh, ublue-os-nvidia-addons.spec
This reverts commit b64843b14ec6fa62e65354a66ad06a88f7c3bcba.
I found that this akmods+hwe change was disabling Wayland. 
Needs more testing before merging again.
=> Revert "feat: swap to negativo17 as nvidia driver source (#170)"

Containerfile.common, README.md, build-kmod-framework-laptop.sh
=> feat: Add framework-laptop kmod

.github/workflows/reusable-build.yml
=> chore: Enable kernel-fsync for F40

.github/workflows/reusable-build.yml
=> chore(ci): Update builder to 24.04

Containerfile.extra
=> fix(zenergy): remove from ASUS build to fix builder

.github/workflows/build-39.yml, .github/workflows/build-40.yml
https://github.com/ublue-os/main/pull/589
https://github.com/ublue-os/hwe/pull/254
=> fix: adjust build schedule based on adjustments to main and hwe

build-prep.sh
=> fix: keys not in place for dkms

.github/workflows/reusable-build.yml
Depends on https://github.com/ublue-os/kernel-cache/pull/26
=> feat: Add support for fsync-ba, an "LTS" version of fsync

README.md
=> fix - added missing wildcard in kmod-nvidia installation guidance

.github/pull_request_template.md
Bring some sanity to bsherman's life.
=> chore(ci): comment out pull request template instructions

.github/workflows/build-39.yml, .github/workflows/build-40.yml, README.md
=> chore: fix workflow yaml

Containerfile.common
=> fix(common): restore xonedo build for asus

.github/workflows/reusable-build.yml
akmods PR needs to merge first
https://github.com/ublue-os/kernel-cache/pull/29
=> feat: add kernel-bazzite

.github/workflows/reusable-build.yml, build-kmod-zfs.sh
Depends on: https://github.com/ublue-os/kernel-cache/pull/33
=> chore: move coreos testing to f41

.github/workflows/cleanup.yml
=> feat(ci): clean up images older than 90 days

.github/workflows/reusable-build.yml
=> chore(ci): Remove unused kernel flavors

.github/workflows/reusable-build.yml, README.md
=> chore(extra): remove extra from kernels other than bazzite, update readme

README.md
=> chore(README): fix dead URLs

build_files/common/build-kmod-openrazer.sh
=> chore: enable openrazer for Fedora 42

build_files/nvidia/ublue-os-nvidia-addons/ublue-os-nvidia-addons.spec
=> fix: rhel macro in nvidia-addons

build_files/zfs/build-kmod-zfs.sh
=> fix: import all openzfs keys

.github/workflows/reusable-build.yml
=> fix: Workflow multiline string

.github/workflows/build-akmods-bazzite.yml, .github/workflows/build-akmods-centos-hsk.yml, .github/workflows/build-akmods-centos.yml, .github/workflows/build-akmods-coreos-stable.yml, .github/workflows/build-akmods-coreos-testing.yml, .github/workflows/build-akmods-longterm-6.12.yml, .github/workflows/build-akmods-main.yml, Justfile
=> fix: Ensure that kernel flavor matches and is not a substring for workflow generation

Containerfile.in
=> fix: restore removed extra kmods

build_files/post/build-post.sh
=> revert: Revert lint cleanup for fpm kmod renaming for now.

Justfile
=> fix: squash RPMs to one layer

Justfile
=> chore: pin coreos-stable kernel version

.github/workflows/reusable-build.yml, build_files/prep/build-prep.sh, build_files/test/test-prep.sh
=> fix: create some empty space by removing weak depts
