ublue-os/akmods

Containerfile
README.md

Upstream provider of the xone akmod is using the latest release of xone which does not yet have support for kernel 6.3. Temporarily disabling until xone releases their 6.3 fix in order to unblock builds.

fix: temporarily disable xone kmod build

---

Containerfile
README.md

xone now has support for kernel 6.3.x
This reverts commit 76806adc856db2163c188125ba7546362282cee2.

Revert "fix: temporarily disable xone kmod build"

---

Containerfile
README.md
build-kmod-jupiter.sh

Jupiter is what Valve shipped with SteamOS, steamdeck is what they submitted upstream. Same driver, but all of Valve's packages point to the name jupiter (or steamdeck-hwmon on main), rendering it useless for it's intended purpose.

fix: Switch to building jupiter driver instead of steamdeck

---

Containerfile
README.md
build-kmod-gasket.sh

Driver needed for Google's Coral TPU hardware on Linux, useful for home servers since it can do ML image processing at very low power usage.
https://coral.ai/products/
Version actually being built here is at https://github.com/KyleGospo/gasket-dkms
We could build upstream, however it has issues preventing it from being unloaded and a few other bugs fixed downstream at OpenSUSE among other places, so this repo serves as a patched source.

feat: Add Google Coral TPU Gasket & Apex drivers

---

Containerfile
README.md
build-kmod-openrgb.sh

Provides modified i2c-piix4 and new i2c-nct6775 for controlling RGB on certain motherboards.

feat: Add OpenRGB kernel modules

---

Containerfile
README.md
build-kmod-wl.sh

This reverts commit 697d57ca8ab0a29b217a6674862bd61bfeec628d, reversing changes made to 4606c64da29576f6f2cea8a1a97d82f18485895f.
This restores the kmod build for the `wl` legacy broadcom driver.  We can do this because of the PR to main https://github.com/ublue-os/main/pull/278 which only includes specific modules in `ublue-os/*-main` images.
By restoring this build, downstream users have the option to include the module if required.

Revert "Merge pull request #20 from EyeCantCU/rm-wl"

---

Containerfile
README.md
build-kmod-evdi.sh

Required for use of the [displaylink](https://www.synaptics.com/products/displaylink-graphics) display standard.

feat: Add evdi kmod for displaylink

---

Containerfile
README.md
build-kmod-nvidia.sh
build-prep.sh
build-ublue-os-nvidia-addons.sh
files/etc/nvidia-container-runtime/config-rootless.toml
files/etc/sway/environment
ublue-os-nvidia-addons.spec

This adds nvidia kmod builds with a parameterized script which uses the nvidia major version to build the rpmfusion provided akmod for the respective nvidia version.
Also this builds the ublue-os-nvidia-addons which includes container runtime repo and sway environment setting for nvidia.
This mostly copies (with minor cleanup) from `ublue-os/nvidia` repo; once merged and building cleanly, the nvidia repo can be modified to build images using the kmods built here.
Only two somewhat significant changes (other than some scripting cleanup) stick out in my mind:
1. since I'm now building both 470 and 535 (and in future i guess this could be more) in a serial fashion, this does cause longer akmods build times, but... it's a daily thing, and the `nvidia` image builds are MUCH faster for when we …

feat: add nvidia kmod builds and ublue-os-nvidia-addons

---

.github/workflows/build.yml
Containerfile.common
Containerfile.nvidia
build-kmod-nvidia.sh
build-prep.sh

In order to make both build time and minimize excess space used by consumers of akmods images, it is helpful to split the nvidia drivers each into their own distinct image.
The original `akmods` image returns to its very small (currently 1.7MB) size, and the new `akmods-nvidia` images will each be only the size of their respective kmod.

feat: split nvidia akmods into distinct images

---

Containerfile.common
build-kmod-xpad-noone.sh

Built in [copr](https://copr.fedorainfracloud.org/coprs/ublue-os/akmods/) from our [xpad-noone](https://github.com/ublue-os/xpad-noone), which is just [upstream](https://github.com/paroj/xpad) with Xbox One controller IDs and vendor IDs [commented out](https://github.com/ublue-os/xpad-noone/commit/c6746b3e0a95a817550a686700eb3cdfe6b27c76#diff-3d985fe7837dec4db1df27733cece3b37633535ef91b1cbdf1c8b6eec4f692db).

feat: Add xpad-noone driver

---

.github/workflows/build.yml

This should fix the problem where `akmods-nvidia` images were not being signed due to improper image name use.

fix: sign akmods-nvidia images properly

---

Containerfile.common
build-kmod-openrazer.sh

Works by masquerading itself as the upstream dkms package with a very high version number so the remaining openrazer packages can be layered as normal.
Spec files are at: https://github.com/ublue-os/openrazer/
Closes #5

feat: Add OpenRazer kmod

---

Containerfile.common
README.md
build-kmod-ryzen-smu.sh

A Linux kernel driver that exposes access to the SMU (System Management Unit) for certain AMD Ryzen Processors.

feat: Add ryzen_smu kmod

---

.github/workflows/build.yml
Containerfile.common
build-prep.sh

An experiment to see how much we need to change for Fedora 39.
The images are now being pushed to Quay for base and silverblue.
I am not expecting many packages to build.  This is just an experiment.

feat: enable builds with Fedora 39

---

.github/workflows/build.yml

This should be merged after https://github.com/ublue-os/main/issues/356 is merged.

chore(ci): restore F39 builds for kmods

---

.github/workflows/build.yml

Prior to this, kernel flavor was never passed so custom kernels were never actually installed

fix(ci): Set kernel flavor in image build args

---

Containerfile.nvidia
files/usr/lib/systemd/system-preset/70-ublue-nvctk-cdi.preset
files/usr/lib/systemd/system/ublue-nvctk-cdi.service
ublue-os-nvidia-addons.spec

This is useful to have nvidia devices ready to go for container use on boot.

feat: auto-generate CDI yaml for nvidia

---

README.md

Gives a better idea what's going on this repo, and adds the missing reference to `ublue-os-nvidia-addons`
Fixes #55

docs: update README to reflect new tagging structure

---

Containerfile.common

These were disabled for the Fedora 39 bringup as they hadn't been built for 39 quite yet, but now that they are, we can enable these

feat: Re-enable Xbox kmods for Fedora 39

---

README.md

ASUS and Surface images do not exist for Fedora 37, and Surface devices with NVIDIA GPUs all support the latest NVIDIA driver

docs(README): Correct organization for custom kernel akmods

---

.github/workflows/build.yml

The Surface kernel for Fedora 39 is ready!

feat: Enable Surface akmods for Fedora 39

---

.github/workflows/build.yml
Containerfile.common
Containerfile.nvidia

This change does two things:
1) uses official upstream `silverblue` image, rather than the QA build of `base`, as our builder
2) changes cron to 1400 UTC to more closely match the time of official image builds
This change matches with the changes in https://github.com/ublue-os/main/pull/407

feat: use official upstream images for kmod builds

---

build-prep.sh

Ah while back, I made a change to akmods/main/nvidia repos to force them to use the same rpmfusion mirror during builds (this gets reset to defaults for resulting images).
This is problematic for F39, since, at the least, it will require a path change due to F39 promoting from "development" to "release".
Should this be removed completely (as I've done in this PR so far) or should we just change the conditional from F39 to F40?

chore: restore default rpmfusion mirror behavior

---

Containerfile.common
build-kmod-xone.sh
build-kmod-xpadneo.sh
ublue-os-akmods-addons.spec

fedora-steam appears to have been dropped with its components relocated to fedora-multimedia

fix(xbox): Replace negativo17 fedora-steam repo with fedora-multimedia

---

ublue-os-akmods-addons.spec

I missed that the version bump was missed in #96 
This corrects that.

chore: fix missing ublue-os-akmods-addons version bump

---

.github/workflows/build.yml
README.md

Thoughts on keeping our builds a bit simpler by not having both nvidia 545 and 535 (which already seems to be deprecated by rpmfusion).

feat: drop nvidia 535 as 545 has replaced it

---

.github/workflows/build.yml
README.md
build-prep.sh

Planned removal of Fedora 37 due to EOL.

feat: Fedora 37 is EOL 2023-12-05

---

build-prep.sh

This consistently pins the build to the same mirror so jobs running on different runners should have the same set of packages to consistently succeed/fail.

chore(ci): pin to single berkley mirror

---

build-ublue-os-akmods-addons.sh

This works around an issue where sometimes negativo17's fedora-multimedia repo was being used instead and pulling the wrong package deps.

chore: prioritize ublue-akmods COPR over other repos

---

.github/workflows/build.yml

Asus custom kernel no longer supports F38, so don't try to build it.
Also cleanup the fsync excludes for F38.

chore(ci): no longer build asus F38

---

.github/workflows/build.yml
Containerfile.common
build-kmod-ayaneo-platform.sh
build-kmod-ayn-platform.sh
build-kmod-bmi160.sh
build-kmod-bmi260.sh
build-kmod-bmi323.sh
build-kmod-evdi.sh
build-kmod-gasket.sh
build-kmod-gcadapter_oc.sh
build-kmod-nct6687d.sh
build-kmod-openrazer.sh
build-kmod-openrgb.sh
build-kmod-rtl8814au.sh
build-kmod-rtl88xxau.sh
build-kmod-ryzen-smu.sh
build-kmod-steamdeck.sh
build-kmod-v4l2loopback.sh
build-kmod-winesync.sh
build-kmod-xone.sh
build-kmod-xpadneo.sh
build-kmod-zenergy.sh
build-prep.sh

This enables Fedora 40 builds, but filters out known problems.
Specifically, when the build version is Fedora 40, this disables several kmods which are either not yet available for Fedora 40 in upstream repos or do not currently compile against Fedora 40.
The disabled kmod list:
- evdi: negativo17 does not yet provide F40
- gasket: compile failure
- nvidia-470xx: compile failure
- rtl18814au: compile failure
- rtl188xxau: compile failure
- v4l2loopback: compile failure
- xpadneo: negativo17 does not yet provide F40
I also standardized a small change to the build-kmod scripts. We now copy/activate extra yum repo files only after getting the Fedora release variable which make things simpler when needing to bail out early due to known issues with F40, etc.

feat: enable preview of Fedora 40 kmod builds

---

Containerfile.common
README.md

This was added primarily for ucore, which is not using it. Removing for now since it's known to fail building in kernel 6.8.

fix: remove gasket kmod build

---

.github/workflows/build.yml

While working on #148 , I noticed the version and linux labels were not working.
These aren't checked anywhere downstream that I know of, so probably didn't break any use case, but should be corrected.

chore: CI fix missing container labels

---

build-kmod-gasket.sh
build-kmod-rtl8814au.sh
build-kmod-rtl88xxau.sh
build-kmod-v4l2loopback.sh

This disables 3 kmods which don't currently build on kernel 6.8:
- rtl8814au
- rtl88xxau
- v4l2loopback
These also happen to fail in F40, since it uses a 6.8 kernel already too.
F40 builds are failing for other reasons at this time and should not block merging of this PR.

fix: don't build certain kmods on kernel 6.8

---

.github/workflows/build-38.yml
.github/workflows/build-39.yml
.github/workflows/build-40.yml
.github/workflows/reusable-build.yml
README.md

This will allow us to see if a specific version of Fedora is building or not, plus allow rebuilding only a specific version.
Extra bonus: this will let us adjust merge checks to require success of a subset of versions, eg "Check all 38 builds successful" and "Check all 39 builds successful" but not 40.
Blocks: https://github.com/ublue-os/main/issues/526

chore(ci): split build workflows by fedora version

---

build-kmod-evdi.sh
build-kmod-v4l2loopback.sh
build-kmod-xpadneo.sh

2 of these and negativo17 who now is supporting F40 in their repos.
v4l2loopback had  not been compiling on 6.8 but now is.

fix: 3 kmods now work on F40

---

.github/workflows/reusable-build.yml
build-kmod-gasket.sh
build-kmod-v4l2loopback.sh

Surface kernel only supports latest.
For some reason v4l2loopback still failing to build on surface's kernel.

chore: disable v4l2loopback on surface and F38 surface

---

.github/workflows/reusable-build.yml
build-kmod-v4l2loopback.sh

Fixes:
- catchup exclude with fsync version change
- don't build fsync for F38
- allow v4l2loopback builds on 6.8, but not custom F39

chore(ci): fix some kmod build failures

---

.github/workflows/reusable-build.yml
README.md
build-kmod-v4l2loopback.sh

Attempting to get akmods building again, at least most of them. #144 is tracking the kmod build gaps, eg, 4 kmods not happy with 6.8 or F40.
- remove nvidia 470 due to rpmfusion dropping support
- no build of v4l2loopback on F38/F39 due to kernel 6.8 problems

chore: support new fedora 6.8.4 main kernel

---

.github/pull_request_template.md

Quick PR template fix for contributor's guide. Note: the link on that page for the code of conduct is also a 404. Currently it is pointing at https://universal-blue.org/CODE_OF_CONDUCT.md

fix: docs: fix contributor's guide 404 link

---

.github/workflows/reusable-build.yml
Containerfile.nvidia
build-kmod-nvidia.sh
build-ublue-os-nvidia-addons.sh
ublue-os-nvidia-addons.spec

This reworks all the bits in akmods for nvidia:
- removes nvidia driver version as only latest is supported
- adds negativo17-fedora-nvidia repo to ublue-os-nvidia-addons RPM
- removes extra metadata from the nvidia-vars create in image
This PR will require a corresponding PR in `hwe` to ensure proper repos are being used and the new package names are installed since negativo17 has some different package naming.

feat: swap to negativo17 as nvidia driver source

---

build-kmod-v4l2loopback.sh

This will merge when it builds cleanly, after rpmfusion migrates the new package from updates-testing to updates repo. 
This will be apparent when:
1) this builds
2) `v4l2loopback` is present here: https://mirror.fcix.net/rpmfusion/free/fedora/updates/39/x86_64/repoview/letter_v.group.html OR "tag" changes to "f39-free-updates" (from testing) here https://koji.rpmfusion.org/koji/buildinfo?buildID=28538
Relates: #144

fix: restore v4l2loopback build

---

.github/workflows/reusable-build.yml

Since we don't know when, if ever, the fedora org on quay.io will have reliable images, stop maintaining a conditional which doesn't get used and makes the workflow more complicated.
Relates: ublue-os/main#78

chore(ci): drop conditional source logic

---

.github/workflows/reusable-build.yml
build-prep.sh

feat: support CoreOS Kernel

---

.github/workflows/reusable-build.yml
Containerfile.common
README.md
build-kmod-zfs.sh
build-prep.sh

chore(ci): Proper Excludes
chore: workaround Tar Bug

feat: ZFS for coreos, GTS version coreos

---

build-prep.sh

Coreos is the only flavor that builds a dkms module. Additionally it's KERNEL_VERSION does not contain .x86_64.

fix: only copy dkms keys for coreos

---

files/etc/sway/environment

Recently flickering on sericea-nvidia was reported in the HWE repo: https://github.com/ublue-os/hwe/issues/260. A workaround or "fix" for a large amount of the flickering on sway is to switch to the vulkan renderer, the nvidia GPUs we support also support the vulkan required extensions and version.
I also added an environment variable that fixes some java applications: _JAVA_AWT_WM_NONREPARENTING=1

fix(nvidia): use vulkan renderer by default to mitigate flickering

---

.github/workflows/reusable-build.yml
build-prep.sh

This provides both kernel streams for uCore or other CoreOS images to consume.
A breaking change occurs in the tagging for existing coreos akmods images.
Instead of: `akmods:coreos-40` and `akmods:coreos-39` this will build
`akmods:coreos-stable-40` and `akmods:coreos-stable-39`.

feat: build both stable and testing CoreOS streams

---

.github/workflows/reusable-build.yml
Containerfile.common
Containerfile.zfs

Initially ZFS support was added as part of the akmods common image and corresponding workflow matrix element.
This splits ZFS support into a distinct:
- workflow matrix element (distinct build)
- Containerfile
- final image

refactor: split zfs into distinct image

---

Containerfile.common
Containerfile.nvidia
build-prep.sh
build-ublue-os-ucore-addons.sh
build-ublue-os-ucore-nvidia.sh
ublue-os-nvidia-addons.spec
ublue-os-ucore-addons.spec
ublue-os-ucore-nvidia.spec

This relocates the ucore-addons and ucore-nvidia RPM builds from ublue-os/ucore-kmods to ublue-os/akmods, allowing us to continue consolidating our build processes into more managable units.
Note: these ucore addons only build when the kernel flavor is set to coreos.

refactor: move ucore addons builds here

---

.github/workflows/reusable-build.yml
Containerfile.nvidia
Containerfile.nvidia-open
build-kmod-nvidia.sh

Enable the open kernel module builds.
This should not affect anything downstream.  Just gets us ready for the switch next Nvidia driver release.
Please note: I have not yet tried booting into an image with this driver.

feat: build nvidia open source kernel module

---

Containerfile.common

Can be restored to extra when build issues in newer kernels are fixed

fix: Remove evdi from common

---

.github/workflows/reusable-build.yml

Matches a change in kernel-cache at: https://github.com/ublue-os/kernel-cache/pull/25
Makes selecting a specific kernel version much easier

feat(ci): Use kernel_version as a build tag

---

Containerfile.extra

Opposite of previous PR, merge me when this module is fixed upstream (Build will not succeed until then).
Moved from common to extra.

feat: Restore evdi to extra

---

.github/workflows/reusable-build.yml

The recent #231 PR replaced fsync with fsync-ba builds, breaking some downstreams, including bluefin.

chore(ci): restore fsync builds

---

Containerfile.common

Asus patches seem to break the xonedo driver.

fix(common): skip xonedo build for asus

---

.github/workflows/build-39.yml
.github/workflows/build-40.yml
README.md

This updates the README to bring in sync with current state.
Also no longer builds akmods just when updating markdown/README file.

docs: update the README to be current

---

Containerfile.common
Containerfile.extra
Containerfile.nvidia
Containerfile.nvidia-open
Containerfile.zfs

Updates the RPM renaming script to read the kernel version from the installed kernel-core RPM, removing that string from the package names if it exists.

chore: refactor package rename script to support all kernel versions

---

build-kmod-xpadneo.sh

negativo17 has added xpadneo for F41.

feat: enable xpadneo for F41

---

Containerfile.nvidia
Containerfile.nvidia-open
files/etc/udev/rules.d/60-nvidia-extra-devices-pm.rules
ublue-os-nvidia-addons.spec

This is a nice-to-have so that any extra USB/Audio devices on nvidia cards are also able to take advantage of powermanagement.
Closes: ublue-os/hwe#291

feat: add udev rules for nvidia extra device PM

---

build-kmod-evdi.sh
build-kmod-xpadneo.sh

chore: enable evdi builds for F41

---

.github/workflows/reusable-build.yml

Don't merge until coreos-stable is on F41 and kernel cache is merged.

feat: enable coreos-stable for F41

---

build-ublue-os-nvidia-addons.sh
test-prep.sh
ublue-os-nvidia-addons.spec

supergfxctl has been relocated to ublue's staging copr

chore(nvidia-addons): Remove supergfxctl copr

---

dual-sign-zfs.sh
dual-sign.sh

rpmrebuild updated from 2.17 to 2.20 in Fedora repos, changing the function function which checks if a package is installed.
This fixes the inputs to that command.

fix: change inputs to rpmrebuild

---

build_files/common/build-kmod-framework-laptop.sh

This is just a minor fix to the log path for kmod build step for framework laptop. This part of the code only gets triggered in case of kmod build failure, hence it has not been caught yet. 
Without this fix, if the kmod build step fails you would not see the build log to be able to debug the issue because the the `find` command will fail with file not found

Fixes typo in the log path for Framewok laptop kmod build

---

.github/actions/get-kernel-version/action.yml
.github/workflows/build-bazzite.yml
.github/workflows/reusable-build.yml
fetch-kernel.sh

Alternative to https://github.com/ublue-os/akmods/pull/309 since I cannot write to it.
Allows for building akmods for prerelease kernels instead of always using the latest tag. Also updates the kernel url and allows for running workflow_dispatch

feat(bazzite): add webhook for bazzite kernel and update url

---

.github/workflows/cleanup.yml
.github/workflows/release-please.yml
.github/workflows/reusable-build.yml

https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
This is a codacy recommendation.
This also fixes the reference to the deprecated release-please repo, to use the new one: https://github.com/googleapis/release-please-action

chore: pin actions to their hashes

---

.github/workflows/build-42.yml
.github/workflows/build-bazzite.yml

Enables the builds for Bazzite and CoreOS kernels in F42 since they were disabled due to failing builds

chore: enable Bazzite and CoreOS kernels

---

.github/workflows/reusable-build.yml
Containerfile.zfs
build_files/shared/build-prep.sh
build_files/shared/check-signatures.sh
build_files/shared/dual-sign.sh
build_files/shared/test-prep.sh
build_files/zfs/dual-sign-zfs.sh

Newer kernels in F42 now require this integrity check for xz compressed kmods. The lack of it was causing failure loading our recompressed kmods on F42.
In addition to the core fix, this includes some tweaks to ensure that rpmfusion works as expected for build/test with/without a single mirror defined, and to support F42 still being "development" in rpmfusion repositories.  
Fixes: #318
See issue for more context.

fix: specify crc32 integrity check when recompressing kmods

---

.github/workflows/build-bazzite.yml

Spring cleaning for the bazzite kernel build options, adds cron and drops f41 builds

chore: fixup bazzite kernel build args

---

.github/workflows/build-41.yml

This isn't used by any downstream projects, no need to build.

chore: don't build bazzite kernel for F41

---

.github/actions/get-kernel-version/action.yml
build_files/shared/build-prep.sh

since coreos-stable is on F42 with a rawhid kernel, this at least lets us try to pin a working version for akmods builds

fix: temporary pin of coreos-stable to 6.13.8-200.fc41.x86_64

---

README.md

This edit reflects updates which have happened to the repo but not been communicated via documentation updates here.
It also emphasizes the Universal Blue use case and de-emphasizes individual custom use though certainly anyone may uses these images if desired.

docs: bring README into sync with reality

---

.github/workflows/build-centos.yml

Re-enabling CentOS bootc 9 builds now that nvidia builds thanks to a quick fix from Negativo17! https://github.com/negativo17/nvidia-driver/issues/178

chore: re-enable centos-bootc:stream9

---

.github/workflows/build-akmods-centos-kmodsig.yml
.github/workflows/reusable-build.yml
.github/workflows/reusable-cache-kernel.yml
Justfile
fetch-kernel.sh
images.yaml

This replaces the Hyperscale (hsk) kernel (which is no longer used by Bluefin LTS) with the CentOS Kmods SIG kernel, now used for Bluefin LTS (HWE).
Closes: #349
Closes: #370

feat: replace centos-hsk kernel with centos-kmodsig

---

Justfile

6.15.9 has the btrfs fixes so we can finally unpin the  stable kernel
undraft once coreOS releases (hopefully today)

chore(kernel): unpin coreos-stable kernel version
